---
_extends: .github

repository:
  name: hs-toxcore
  description: Haskell Tox protocol implementation
  homepage: https://toktok.ltd/spec
  topics: haskell, toxcore, network, p2p
  has_issues: true

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - build_android
          - cirrus-ci
          - Codacy Static Code Analysis
          - code-review/reviewable
