---
_extends: .github

repository:
  name: hs-toxcore
  description: Haskell Tox protocol implementation
  homepage: https://toktok.ltd/spec
  topics: haskell, toxcore, network, p2p
  has_issues: true

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - "android-aarch64"
          - "android-arm"
          - "android-i686"
          - "android-x86_64"
          - "build"
          - "cirrus-ci"
          - "Codacy Static Code Analysis"
          - "code-review/reviewable"
