---
cache:
  - '%APPDATA%\cabal'
  - '%APPDATA%\ghc'
  - '%APPDATA%\stack'

install:
  - choco install ghc --version 8.2.2
  - choco install haskell-stack
  - curl https://download.libsodium.org/libsodium/releases/libsodium-1.0.17-mingw.tar.gz | tar zx
  - refreshenv
  - cabal update
  - cabal install happy --overwrite-policy=always

build_script:
  - stack --no-terminal build --extra-include-dirs=%CD%\libsodium-win64\include --extra-lib-dirs=%CD%\libsodium-win64\lib

test_script:
  - stack --no-terminal test --extra-include-dirs=%CD%\libsodium-win64\include --extra-lib-dirs=%CD%\libsodium-win64\lib
